#server:
#  port: 8085
#  servlet:
#    context-path: /identity
#
#spring:
#  datasource:
#    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/identity_service}
#    driverClassName: "com.mysql.cj.jdbc.Driver"
#    password: ${DBMS_PASSWORD:28082001}
#    username: ${DBMS_USERNAME:root}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
##  M9ebpI+8t3asjzq0M/hMUmWFLLFfp/RjTqB5DLc2EXSm01nVDWnHCAtKozeFMQC4
##  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
#jwt:
#  signerKey: "M9ebpI+8t3asjzq0M/hMUmWFLLFfp/RjTqB5DLc2EXSm01nVDWnHCAtKozeFMQC4"
#  valid-duration: 3600 # in second
#  refreshable-duration: 36000 # in seconds

server:
  port: 9090

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/identity_service4}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:28082001}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    enable: true
  group-configs:
    - group: advancedRealEstate_BE
      paths-to-match: /api/**